version: 2.1

jobs:
  build_and_check:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run:
          name: Authenticate with Google Cloud
          command: |
            echo $GCP_SERVICE_ACCOUNT_KEY | gcloud auth activate-service-account --key-file=-
            gcloud auth list
      - run:
          name: Build with Maven
          command: mvn clean install

workflows:
  version: 2
  login_and_build:
    jobs:
      - build_and_check