version: 2.1

jobs:
  verify-1password-integration:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Verify 1Password Integration
          command: |
            # Fetch the 1Password token from the context
            export OP_TOKEN=$OP_SERVICE_ACCOUNT_TOKEN

            # Perform some verification using the 1Password API
            # Replace this with your actual verification logic
            curl -X GET \
              -H "Authorization: Bearer $OP_TOKEN" \
              "https://example.1password.com/api/v1/some-endpoint"

workflows:
  version: 2
  build:
    jobs:
      - verify-1password-integration:
          context: 1pass_cred
