version: 2.1

jobs:
  list-1password-vaults:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install 1Password CLI
          command: |
            wget -O op.tar.gz https://downloads.1password.com/command-line/1password-cli-2.12.0-linux.tar.gz
            tar -xzf op.tar.gz -C /usr/local/bin/
            rm op.tar.gz

      - run:
          name: Authenticate with 1Password
          command: |
            export OP_SESSION=$(op signin my $OP_SERVICE_ACCOUNT_EMAIL $OP_SERVICE_ACCOUNT_SECRET)

      - run:
          name: List 1Password Vaults
          command: |
            op list vaults

workflows:
  version: 2
  build:
    jobs:
      - list-1password-vaults:
          context: 1pass_cred
