version: 2.1

jobs:
  list-1password-vaults:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install 1Password CLI
          command: |
            curl -sS https://cache.agilebits.com/dist/1P/op/pkg/v2.12.0/op_linux_amd64_v2.12.0.tar.gz -o op.tar.gz
            tar -xzf op.tar.gz -C /usr/local/bin/
            rm op.tar.gz

      - run:
          name: Authenticate with 1Password
          command: |
            export OP_SESSION=$(op signin my $OP_SERVICE_ACCOUNT_EMAIL $OP_SERVICE_ACCOUNT_SECRET)

      - run:
          name: List 1Password Vaults
          command: |
            op list vaults

workflows:
  version: 2
  build:
    jobs:
      - list-1password-vaults:
          context: 1pass_cred
