version: 2.1

executors:
  gcloud:
    docker:
      - image: google/cloud-sdk:latest

commands:
  authenticate_gcloud:
    description: Authenticate with GCP.
    steps:
      - run:
          name: Authenticate with Google Cloud
          command: |
            echo $GCP_SERVICE_ACCOUNT_KEY | gcloud auth activate-service-account --key-file=-
            gcloud auth list

jobs:
  gcp_login_check:
    executor: gcloud
    steps:
      - authenticate_gcloud

workflows:
  version: 2
  login_check:
    jobs:
      - gcp_login_check


