version: 2.1

executors:
  default:
    docker:
      - image: circleci/openjdk:11-jdk

jobs:
  build:
    executor: default
    steps:
      - checkout
      - run:
          name: Install GCP CLI
          command: |
            echo 'export PATH=$PATH:/opt/google-cloud-sdk/bin' >> $BASH_ENV
            sudo apt-get update
            sudo apt-get install -y curl apt-transport-https lsb-release software-properties-common
            curl -sSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
            echo "deb https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
            sudo apt-get update && sudo apt-get install google-cloud-sdk
      - run:
          name: Authenticate to GCP
          command: |
            # Set the GCP service account key from the context as an environment variable
            echo $GCP_SA_KEY | base64 --decode > /tmp/gcp_sa_key.json            # Authenticate using the service account key
            gcloud auth activate-service-account --key-file=/tmp/gcp_sa_key.json            # Set the GCP project ID
            gcloud config set project "test-script"

      - run:
          name: Decode Base64
          command: |
           input_data="SGVsbG8gd29ybGQh"
           decoded_data=$(echo -n $input_data | base64 --decode)
           echo $decoded_data
         
      - run:
          name: Build and Test

          command: |
            mvn clean install


workflows:
  version: 2
  build:
    jobs:
      - build:
          context: gcp-auth
