version: 2.1

<<<<<<< HEAD
jobs:
  build_and_check:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run:
          name: Install Google Cloud SDK
          command: |
            echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
            sudo apt-get update && sudo apt-get install google-cloud-sdk

      - run:
          name: Set up Google Cloud credentials
          command: |
            echo $GCP_SERVICE_ACCOUNT_KEY > /tmp/service-account.json
            echo 'export GOOGLE_APPLICATION_CREDENTIALS=/tmp/service-account.json' >> $BASH_ENV
      - run:
          name: Authenticate with Google Cloud
          command: |
            gcloud auth activate-service-account --key-file=/tmp/service-account.json
            gcloud auth list
      - run:
          name: Build with Maven
          command: mvn clean install

workflows:
  version: 2
  login_and_build:
    jobs:
      - build_and_check
=======
executors:
  gcloud:
    docker:
      - image: google/cloud-sdk:latest

commands:
  authenticate_gcloud:
    description: Authenticate with GCP.
    steps:
      - run:
          name: Authenticate with Google Cloud
          command: |
            echo $GCP_SERVICE_ACCOUNT_KEY | gcloud auth activate-service-account --key-file=-
            gcloud auth list

jobs:
  gcp_login_check:
    executor: gcloud
    steps:
      - authenticate_gcloud

workflows:
  version: 2
  login_check:
    jobs:
      - gcp_login_check


>>>>>>> 485330f63d723ae2c4cdf7ffe02af5285bf3f010
