version: 2.1

jobs:
  list-1password-vaults:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run:
          name: Add 1Password CLI Repository
          command: |
            echo https://downloads.1password.com/linux/alpinelinux/stable/ >> /etc/apk/repositories
            wget https://downloads.1password.com/linux/keys/alpinelinux/support@1password.com-61ddfc31.rsa.pub -P /etc/apk/keys
            apk update

      - run:
          name: Install 1Password CLI
          command: |
            apk add 1password-cli

      - run:
          name: Authenticate with 1Password
          command: |
              export OP_SERVICE_ACCOUNT_TOKEN=$OP_SERVICE_ACCOUNT_TOKEN

      - run:
          name: list the user
          command: | 
              op user get --me 
      - run:
          name: List 1Password Vaults
          command: |
            # Assuming GCP_SERVICE_ACCOUNT_KEY contains the service account key
            echo $GCP_SERVICE_ACCOUNT_KEY > /tmp/service-account.json

<<<<<<< HEAD
            op document list #
=======
            op document list 
>>>>>>> f85214a3e8a2c405b3cae8840a9f2e8a9cb6d6f9
            
            op vault ls 

workflows:
  version: 2
  build:
    jobs:
      - list-1password-vaults:
          context: 1pass_cred

