version: 2.1

jobs:
  build_and_check:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run:
          name: Install Google Cloud SDK
          command: |
            # ... (same as above to install gcloud)
      - run:
          name: Set up Google Cloud credentials
          command: |
            echo $GCP_SERVICE_ACCOUNT_KEY > /tmp/service-account.json
            echo 'export GOOGLE_APPLICATION_CREDENTIALS=/tmp/service-account.json' >> $BASH_ENV
      - run:
          name: Authenticate with Google Cloud
          command: |
            gcloud auth activate-service-account --key-file=/tmp/service-account.json
            gcloud auth list
      - run:
          name: Build with Maven
          command: mvn clean install

workflows:
  version: 2
  login_and_build:
    jobs:
      - build_and_checkversion: 2.1

jobs:
  build_and_check:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run:
          name: Install Google Cloud SDK
          command: |
            # ... (same as above to install gcloud)
      - run:
          name: Set up Google Cloud credentials
          command: |
            echo $GCP_SERVICE_ACCOUNT_KEY > /tmp/service-account.json
            echo 'export GOOGLE_APPLICATION_CREDENTIALS=/tmp/service-account.json' >> $BASH_ENV
      - run:
          name: Authenticate with Google Cloud
          command: |
            gcloud auth activate-service-account --key-file=/tmp/service-account.json
            gcloud auth list
      - run:
          name: Build with Maven
          command: mvn clean install

workflows:
  version: 2
  login_and_build:
    jobs:
      - build_and_check
