version: 2.1

jobs:
  list-1password-vaults:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install 1Password CLI
          command: |
            ARCH="<choose between 386/amd64/arm/arm64>" && \
            wget "https://cache.agilebits.com/dist/1P/op2/pkg/v2.20.0/op_linux_${ARCH}_v2.20.0.zip" -O op.zip && \
            unzip -d op op.zip && \
            sudo mv op/op /usr/local/bin && \
            rm -r op.zip op && \
            sudo groupadd -f onepassword-cli && \
            sudo chgrp onepassword-cli /usr/local/bin/op && \
            sudo chmod g+s /usr/local/bin/op
      - run:
          name: Authenticate with 1Password
          command: |
            export OP_SESSION=$(op signin my $OP_SERVICE_ACCOUNT_EMAIL $OP_SERVICE_ACCOUNT_SECRET)

      - run:
          name: List 1Password Vaults
          command: |
            op list vaults

workflows:
  version: 2
  build:
    jobs:
      - list-1password-vaults:
          context: 1pass_cred
