version: 2.1

jobs:
  authenticate-with-1password-and-gcp:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - run:
          name: Install 1Password CLI
          command: |
            curl -sS https://downloads.1password.com/command-line/1password-cli-2.12.0-linux.tar.gz -o op.tar.gz
            tar -xzf op.tar.gz -C /usr/local/bin/
            rm op.tar.gz

      - run:
          name: Authenticate with 1Password and Retrieve GCP Key
          command: |
            export OP_SESSION=$(op signin my $OP_SERVICE_ACCOUNT_EMAIL $OP_SERVICE_ACCOUNT_SECRET)
            GCP_KEY=$(op get document gcp_credentials/gcp_key)

      - run:
          name: Save GCP Key to File
          command: echo "$GCP_KEY" > gcp-key.json

      - run:
          name: Authenticate with GCP
          command: |
            gcloud auth activate-service-account --key-file=gcp-key.json

      - run:
          name: List 1Password Vaults
          command: |
            op list vaults

      # Your additional steps using GCP authentication go here
      - run:
          name: Run GCP Commands
          command: |
            gcloud compute instances list

workflows:
  version: 2
  build:
    jobs:
      - authenticate-with-1password-and-gcp:
          context: 1pass_cred
