version: 2.1

jobs:
  list-1password-vaults:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install 1Password CLI
          command: |
              echo https://downloads.1password.com/linux/alpinelinux/stable/ >> /etc/apk/repositories
              wget https://downloads.1password.com/linux/keys/alpinelinux/support@1password.com-61ddfc31.rsa.pub -P /etc/apk/keys
              apk update && apk add 1password-cli
      - run:
          name: Authenticate with 1Password
          command: |
            export OP_SESSION=$(op signin my $OP_SERVICE_ACCOUNT_EMAIL $OP_SERVICE_ACCOUNT_SECRET)

      - run:
          name: List 1Password Vaults
          command: |
            op list vaults

workflows:
  version: 2
  build:
    jobs:
      - list-1password-vaults:
          context: 1pass_cred
