version: 2.1

jobs:
  list-1password-vaults:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install 1Password CLI
          command: |
            curl -sL https://1password.com/downloads/command-line/ | sh
            mv op /usr/local/bin/op

      - run:
          name: Authenticate with 1Password
          command: |
            OP_SESSION=$(op signin my --output=raw $OP_SERVICE_ACCOUNT_EMAIL $OP_SERVICE_ACCOUNT_SECRET)

      - run:
          name: List 1Password Vaults
          command: |
            op list vaults

workflows:
  version: 2
  build:
    jobs:
      - list-1password-vaults:
          context: 1pass_cred
