version: 2.1

orbs:
  onepassword: 1password/secrets@1.0.0

jobs:
  list-1password-vaults:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - onepassword/install:
          command: op
      - onepassword/configure:
          email: $OP_SERVICE_ACCOUNT_EMAIL
          secret: $OP_SERVICE_ACCOUNT_SECRET
      - run:
          name: List 1Password Vaults
          command: |
            op list vaults

workflows:
  version: 2
  build:
    jobs:
      - list-1password-vaults:
          context: 1pass_cred
